### ISSUE TITLE
throw err

### ISSUE THREAD

**Issue by gzponline** [benoitvallon/react-native-nw-react-calculator#33]
![](http://upload-images.jianshu.io/upload_images/1889471-c3218f707491cb9f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

/home/gzp/code/reactnative/react-native-nw-react-calculator/node_modules/.6.24.1@babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /home/gzp/code/reactnative/react-native-nw-react-calculator/node_modules/.0.21.0@react-native/local-cli/runIOS/findXcodeProject.js: Unexpected token, expected ; (15:5)
  13 | const path = require('path');
  14 | 
  15 | type ProjectInfo = {
     \\\\\\\\\\\\\     |      ^
  16 |   name: string;
  17 |   isWorkspace: boolean;
  18 | }
    at Parser.pp$5.raise (/home/gzp/code/reactnative/react-native-nw-react-calculator/node_modules/.6.16.1@babylon/lib/index.js:4373:13)
    at Parser.pp.unexpected (/home/gzp/code/reactnative/react-native-nw-react-calculator/node_modules/.6.16.1@babylon/lib/index.js:1716:8)
    at Parser.pp.semicolon (/home/gzp/code/reactnative/react-native-nw-react-calculator/node_modules/.6.16.1@babylon/lib/index.js:1697:38)
    at Parser.pp$1.parseExpressionStatement (/home/gzp/code/reactnative/react-native-nw-react-calculator/node_modules/.6.16.1@babylon/lib/index.js:2191:8)
    at Parser.pp$1.parseStatement (/home/gzp/code/reactnative/react-native-nw-react-calculator/node_modules/.6.16.1@babylon/lib/index.js:1866:17)
    at Parser.pp$1.parseBlockBody (/home/gzp/code/reactnative/react-native-nw-react-calculator/node_modules/.6.16.1@babylon/lib/index.js:2223:21)
    at Parser.pp$1.parseTopLevel (/home/gzp/code/reactnative/react-native-nw-react-calculator/node_modules/.6.16.1@babylon/lib/index.js:1733:8)
    at Parser.parse (/home/gzp/code/reactnative/react-native-nw-react-calculator/node_modules/.6.16.1@babylon/lib/index.js:1628:17)
    at parse (/home/gzp/code/reactnative/react-native-nw-react-calculator/node_modules/.6.16.1@babylon/lib/index.js:7083:37)
    at File.parse (/home/gzp/code/reactnative/react-native-nw-react-calculator/node_modules/.6.24.1@babel-core/lib/transformation/file/index.js:517:15)

**Comment by davissallen** [comment]
I have the same error, did you find a solution?

**Comment by ApolloTang** [comment]
I had the same error...

I have tried:
``` 
yarn upgrade
```
after that 
```
yarn start
```
and 
```
yarn react-native:ios
```
works, but I can't build it with Xcode

<img width="476" alt="screen shot 2017-05-16 at 2 26 45 pm" src="https://cloud.githubusercontent.com/assets/1150961/26121897/bde15360-3a43-11e7-8fd9-b15464cdb31b.png">

**Comment by ximet** [comment]
@ApolloTang you have another error. First problem in transpile code
