### ISSUE TITLE
throw er when use npm run server-webrun

### ISSUE THREAD

**Issue by murking** [benoitvallon/react-native-nw-react-calculator#43]
> ReactNativeNWReactCalculator@1.0.0 start /Users/zjh-mac/Documents/react/react-native-nw-react-calculator-master
> node node_modules/react-native/local-cli/cli.js start

 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/zjh-mac/Documents/react/react-native-nw-react-calculator-master 

[下午8:33:55] <START> Building Dependency Graph
[下午8:33:55] <START> Crawling File System
(node:5844) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[Hot Module Replacement] Server listening on /hot

React packager ready.

2018-04-14 20:34 node[5844] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-04-14 20:34 node[5844] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-04-14 20:34 node[5844] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"errno":"EMFILE","code":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1003:13)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1382:9)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ReactNativeNWReactCalculator@1.0.0 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ReactNativeNWReactCalculator@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zjh-mac/.npm/_logs/2018-04-14T12_34_01_174Z-debug.log
zjh-macdeMacBook-Pro:react-native-nw-react-calculator-master zjh-mac$ npm run server-web
npm ERR! missing script: server-web

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zjh-mac/.npm/_logs/2018-04-14T12_34_38_857Z-debug.log

**Comment by murking** [comment]
npm version :5.6.0
have already run npm install
